package com.xhpower.education.platform.entity;

import java.io.Serializable;
import java.util.Date;

import com.baomidou.mybatisplus.annotations.TableField;
import com.baomidou.mybatisplus.annotations.TableName;

/**
 * 
* @ClassName: BannerEntity 
* @Description: 轮播图实体类 
* @author xiong li 
* @date 2017年8月26日 下午3:23:29 
*
 */
@TableName("np_banner")
public class BannerEntity implements Serializable {
    /** 
	* @Fields serialVersionUID : 序列化ID
	*/ 
	private static final long serialVersionUID = -1984125502011986767L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner.location
     *
     * @mbggenerated
     */
    private String location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner.img
     *
     * @mbggenerated
     */
    private String img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner.from
     *
     * @mbggenerated
     */
    @TableField("up_down")
    private String upDown;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner.sort
     *
     * @mbggenerated
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner.locationtext
     *
     * @mbggenerated
     */
    @TableField("location_text")
    private String locationText;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner.url_type
     *
     * @mbggenerated
     */
    @TableField("url_type")
    private String urlType;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner.create_time
     *
     * @mbggenerated
     */
    @TableField("create_time")
    private Date createTime;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner.update_time
     *
     * @mbggenerated
     */
    @TableField("update_time")
    private Date updateTime;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner.source
     *
     * @mbggenerated
     */
    private Integer source;
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner.source
     *
     * @return the value of banner.source
     *
     * @mbggenerated
     */
    public Integer getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner.source
     *
     * @param id the value for banner.source
     *
     * @mbggenerated
     */
    public void setSource(Integer source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner.id
     *
     * @return the value of banner.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner.id
     *
     * @param id the value for banner.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner.url
     *
     * @return the value of banner.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner.url
     *
     * @param url the value for banner.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner.title
     *
     * @return the value of banner.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner.title
     *
     * @param title the value for banner.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner.location
     *
     * @return the value of banner.location
     *
     * @mbggenerated
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner.location
     *
     * @param location the value for banner.location
     *
     * @mbggenerated
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner.img
     *
     * @return the value of banner.img
     *
     * @mbggenerated
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner.img
     *
     * @param img the value for banner.img
     *
     * @mbggenerated
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner.upDown
     *
     * @return the value of banner.upDown
     *
     * @mbggenerated
     */
    public String getUpDown() {
        return upDown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner.upDown
     *
     * @param from the value for banner.upDown
     *
     * @mbggenerated
     */
    public void setUpDown(String upDown) {
        this.upDown = upDown == null ? null : upDown.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner.sort
     *
     * @return the value of banner.sort
     *
     * @mbggenerated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner.sort
     *
     * @param sort the value for banner.sort
     *
     * @mbggenerated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner.type
     *
     * @return the value of banner.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner.type
     *
     * @param type the value for banner.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner.location_text
     *
     * @return the value of banner.location_text
     *
     * @mbggenerated
     */
    public String getLocationText() {
        return locationText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner.locationtext
     *
     * @param locationtext the value for banner.locationtext
     *
     * @mbggenerated
     */
    public void setLocationText(String locationText) {
        this.locationText = locationText == null ? null : locationText.trim();
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner.urlType
     *
     * @return the value of banner.urlType
     *
     * @mbggenerated
     */
    public String getUrlType() {
        return urlType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner.urlType
     *
     * @param locationtext the value for banner.urlType
     *
     * @mbggenerated
     */
    public void setUrlType(String urlType) {
        this.urlType = urlType == null ? null : urlType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner.createTime
     *
     * @param locationtext the value for banner.createTime
     *
     * @mbggenerated
     */
	public Date getCreateTime() {
		return createTime;
	}

	 /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner.createTime
     *
     * @param locationtext the value for banner.createTime
     *
     * @mbggenerated
     */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	 /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner.updateTime
     *
     * @param locationtext the value for banner.updateTime
     *
     * @mbggenerated
     */
	public Date getUpdateTime() {
		return updateTime;
	}

	 /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner.updateTime
     *
     * @param locationtext the value for banner.updateTime
     *
     * @mbggenerated
     */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}