package com.xhpower.education.platform.entity;

import java.util.Date;

import com.baomidou.mybatisplus.annotations.TableField;
import com.baomidou.mybatisplus.annotations.TableName;

@TableName("np_expert")
public class ExpertEntity  {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert.achievement
     *
     * @mbggenerated
     */
    private String achievement;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert.recommend
     *
     * @mbggenerated
     */
    private Integer recommend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert.unit
     *
     * @mbggenerated
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert.sort
     *
     * @mbggenerated
     */
    @TableField("logic_status")
    private Integer logicStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert.tag
     *
     * @mbggenerated
     */
    private String tag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert.createtime
     *
     * @mbggenerated
     */
    @TableField("create_time")
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert.updatetime
     *
     * @mbggenerated
     */
    @TableField("update_time")
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert.synopsis
     *
     * @mbggenerated
     */
    private String synopsis;
    @TableField("is_top")
    private Integer isTop;
    @TableField("expert_img")
    private String expertImg;
    @TableField("teach_situ")
    private String teachSitu;
    @TableField("scific_res")
    private String scificRes;
    @TableField("scific_awards")
    private String scificAwards;
    
    private Integer attention;
    
    private String topic;
    @TableField("topic_ids")
    private String topicIds;
    private String section;
    @TableField("section_id")
    private String sectionId;
	/**账号*/
	private String telephone;
	/**密码*/
	private String password;
	/**性别*/
	private String sex;
	/**邮箱*/
	private String email;
	/**提问费用*/
	private String charge; 
	/**收费比例*/
	@TableField("charge_rate")
	private String chargeRate; 
	@TableField("user_id")
	private Integer userId;
	

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert.id
     *
     * @return the value of expert.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert.id
     *
     * @param id the value for expert.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert.name
     *
     * @return the value of expert.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert.name
     *
     * @param name the value for expert.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert.achievement
     *
     * @return the value of expert.achievement
     *
     * @mbggenerated
     */
    public String getAchievement() {
        return achievement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert.achievement
     *
     * @param achievement the value for expert.achievement
     *
     * @mbggenerated
     */
    public void setAchievement(String achievement) {
        this.achievement = achievement == null ? null : achievement.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert.recommend
     *
     * @return the value of expert.recommend
     *
     * @mbggenerated
     */
    public Integer getRecommend() {
        return recommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert.recommend
     *
     * @param recommend the value for expert.recommend
     *
     * @mbggenerated
     */
    public void setRecommend(Integer recommend) {
        this.recommend = recommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert.status
     *
     * @return the value of expert.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert.status
     *
     * @param status the value for expert.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert.unit
     *
     * @return the value of expert.unit
     *
     * @mbggenerated
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert.unit
     *
     * @param unit the value for expert.unit
     *
     * @mbggenerated
     */
    public void setUnit(String unit) {
        this.unit = unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert.sort
     *
     * @return the value of expert.sort
     *
     * @mbggenerated
     */
    public Integer getLogicStatus() {
        return logicStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert.sort
     *
     * @param sort the value for expert.sort
     *
     * @mbggenerated
     */
    public void setLogicStatus(Integer logicStatus) {
        this.logicStatus = logicStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert.tag
     *
     * @return the value of expert.tag
     *
     * @mbggenerated
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert.tag
     *
     * @param tag the value for expert.tag
     *
     * @mbggenerated
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert.createtime
     *
     * @return the value of expert.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert.createtime
     *
     * @param createtime the value for expert.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert.updatetime
     *
     * @return the value of expert.updatetime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert.updatetime
     *
     * @param updatetime the value for expert.updatetime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert.synopsis
     *
     * @return the value of expert.synopsis
     *
     * @mbggenerated
     */
    public String getSynopsis() {
        return synopsis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert.synopsis
     *
     * @param synopsis the value for expert.synopsis
     *
     * @mbggenerated
     */
    public void setSynopsis(String synopsis) {
        this.synopsis = synopsis == null ? null : synopsis.trim();
    }
    
    public Integer getIsTop() {
		return isTop;
	}

	public void setIsTop(Integer isTop) {
		this.isTop = isTop;
	}

	public String getExpertImg() {
		return expertImg;
	}

	public void setExpertImg(String expertImg) {
		this.expertImg = expertImg;
	}

	public Integer getAttention() {
		return attention;
	}

	public void setAttention(Integer attention) {
		this.attention = attention;
	}

	public String getTeachSitu() {
		return teachSitu;
	}

	public void setTeachSitu(String teachSitu) {
		this.teachSitu = teachSitu;
	}

	public String getTopic() {
		return topic;
	}

	public void setTopic(String topic) {
		this.topic = topic;
	}

	public String getScificRes() {
		return scificRes;
	}

	public void setScificRes(String scificRes) {
		this.scificRes = scificRes;
	}

	public String getScificAwards() {
		return scificAwards;
	}

	public void setScificAwards(String scificAwards) {
		this.scificAwards = scificAwards;
	}

	public String getTelephone() {
		return telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getSex() {
		return sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getSection() {
		return section;
	}

	public void setSection(String section) {
		this.section = section;
	}

	public String getCharge() {
		return charge;
	}

	public void setCharge(String charge) {
		this.charge = charge;
	}

	public String getChargeRate() {
		return chargeRate;
	}

	public void setChargeRate(String chargeRate) {
		this.chargeRate = chargeRate;
	}

	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getTopicIds() {
		return topicIds;
	}

	public void setTopicIds(String topicIds) {
		this.topicIds = topicIds;
	}

	public String getSectionId() {
		return sectionId;
	}

	public void setSectionId(String sectionId) {
		this.sectionId = sectionId;
	}
	
}