package com.xhpower.education.platform.entity;

import java.io.Serializable;
import java.util.Date;

import com.baomidou.mybatisplus.activerecord.Model;
import com.baomidou.mybatisplus.annotations.TableField;
import com.baomidou.mybatisplus.annotations.TableName;

@TableName(value = "np_questions")
public class QuestionsEntity extends Model<QuestionsEntity> implements java.io.Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questions.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questions.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questions.tag
     *
     * @mbggenerated
     */
    private String tag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questions.attention
     *
     * @mbggenerated
     */
    private Integer attention;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questions.browse
     *
     * @mbggenerated
     */
    private Long browse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questions.create_user
     *
     * @mbggenerated
     */
    @TableField("create_user")
    private Integer createUser;
    
    @TableField(exist=false)
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questions.createdate
     *
     * @mbggenerated
     */
    @TableField("create_date")
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questions.updatetime
     *
     * @mbggenerated
     */
    @TableField("update_time")
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questions.describe
     *
     * @mbggenerated
     */
    private String describ;
    
    /**标签Ids*/
    @TableField("tag_ids")
	private String tagIds;
	
	/**主题*/
    @TableField("topic_ids")
	private String topicIds;

	/**学段id*/
    @TableField("period_id")
	private String periodId;

	/**评论数*/
	private Integer comments;
	
	/**问题来源*/
	private String source;
	
	/**主题名称*/
	@TableField("topic_names")
	private String topicNames;

	/**学段名称*/
	@TableField("period_name")
	private String periodName;

	/**年级id*/
	@TableField("grade_id")
	private String gradeId;

	/**年级名称*/
	@TableField("grade_name")
	private String gradeName;
	
	/**审核状态 0：未审核 1：已审核 2:审核不通过*/
	private Integer status;
	

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questions.id
     *
     * @return the value of questions.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questions.id
     *
     * @param id the value for questions.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questions.name
     *
     * @return the value of questions.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questions.name
     *
     * @param name the value for questions.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questions.tag
     *
     * @return the value of questions.tag
     *
     * @mbggenerated
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questions.tag
     *
     * @param tag the value for questions.tag
     *
     * @mbggenerated
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questions.attention
     *
     * @return the value of questions.attention
     *
     * @mbggenerated
     */
    public Integer getAttention() {
        return attention;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questions.attention
     *
     * @param attention the value for questions.attention
     *
     * @mbggenerated
     */
    public void setAttention(Integer attention) {
        this.attention = attention;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questions.browse
     *
     * @return the value of questions.browse
     *
     * @mbggenerated
     */
    public Long getBrowse() {
        return browse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questions.browse
     *
     * @param browse the value for questions.browse
     *
     * @mbggenerated
     */
    public void setBrowse(Long browse) {
        this.browse = browse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questions.createuser
     *
     * @return the value of questions.createuser
     *
     * @mbggenerated
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questions.createuser
     *
     * @param createuser the value for questions.createuser
     *
     * @mbggenerated
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questions.createdate
     *
     * @return the value of questions.createdate
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questions.createdate
     *
     * @param createdate the value for questions.createdate
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questions.updatetime
     *
     * @return the value of questions.updatetime
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questions.updatetime
     *
     * @param updatetime the value for questions.updatetime
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questions.describ
     *
     * @return the value of questions.describ
     *
     * @mbggenerated
     */
    public String getDescrib() {
        return describ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questions.describ
     *
     * @param describe the value for questions.describ
     *
     * @mbggenerated
     */
    public void setDescrib(String describ) {
        this.describ = describ == null ? null : describ.trim();
    }
    
    public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getTagIds() {
		return tagIds;
	}

	public void setTagIds(String tagIds) {
		this.tagIds = tagIds;
	}

	public String getTopicIds() {
		return topicIds;
	}

	public void setTopicIds(String topicIds) {
		this.topicIds = topicIds;
	}

	public String getPeriodId() {
		return periodId;
	}

	public void setPeriodId(String periodId) {
		this.periodId = periodId;
	}

	public Integer getComments() {
		return comments;
	}

	public void setComments(Integer comments) {
		this.comments = comments;
	}

	public String getSource() {
		return source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	public String getTopicNames() {
		return topicNames;
	}

	public void setTopicNames(String topicNames) {
		this.topicNames = topicNames;
	}

	public String getPeriodName() {
		return periodName;
	}

	public void setPeriodName(String periodName) {
		this.periodName = periodName;
	}

	public String getGradeId() {
		return gradeId;
	}

	public void setGradeId(String gradeId) {
		this.gradeId = gradeId;
	}

	public String getGradeName() {
		return gradeName;
	}

	public void setGradeName(String gradeName) {
		this.gradeName = gradeName;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Override
    protected Serializable pkVal() {
        return this.id;
    }
}